export const champions = [
	{ id: 1, name: "Aatrox", image: "/champions/Aatrox.png", roles: ["top"] },
	{ id: 2, name: "Ahri", image: "/champions/Ahri.png", roles: ["mid"] },
	{ id: 3, name: "Akali", image: "/champions/Akali.png", roles: ["mid"] },
	{ id: 4, name: "Akshan", image: "/champions/Akshan.png", roles: ["mid"] },
	{ id: 5, name: "Alistar", image: "/champions/Alistar.png", roles: ["support"] },
	{ id: 6, name: "Ambessa", image: "/champions/Ambessa.png", roles: ["top"] },
	{ id: 7, name: "Amumu", image: "/champions/Amumu.png", roles: ["jungle"] },
	{ id: 8, name: "Anivia", image: "/champions/Anivia.png", roles: ["mid"] },
	{ id: 9, name: "Annie", image: "/champions/Annie.png", roles: ["mid"] },
	{ id: 10, name: "Aphelios", image: "/champions/Aphelios.png", roles: ["adc"] },
	{ id: 11, name: "Ashe", image: "/champions/Ashe.png", roles: ["adc", "support"] },
	{ id: 12, name: "Aurelion Sol", image: "/champions/AurelionSol.png", roles: ["mid"] },
	{ id: 13, name: "Aurora", image: "/champions/Aurora.png", roles: ["mid", "top"] },
	{ id: 14, name: "Azir", image: "/champions/Azir.png", roles: ["mid"] },
	{ id: 15, name: "Bard", image: "/champions/Bard.png", roles: ["support"] },
	{ id: 16, name: "Bel'Veth", image: "/champions/Belveth.png", roles: ["jungle"] },
	{ id: 17, name: "Blitzcrank", image: "/champions/Blitzcrank.png", roles: ["support"] },
	{ id: 18, name: "Brand", image: "/champions/Brand.png", roles: ["support"] },
	{ id: 19, name: "Braum", image: "/champions/Braum.png", roles: ["support"] },
	{ id: 20, name: "Briar", image: "/champions/Briar.png", roles: ["jungle"] },
	{ id: 21, name: "Caitlyn", image: "/champions/Caitlyn.png", roles: ["adc"] },
	{ id: 22, name: "Camille", image: "/champions/Camille.png", roles: ["top"] },
	{ id: 23, name: "Cassiopeia", image: "/champions/Cassiopeia.png", roles: ["mid"] },
	{ id: 24, name: "Cho'Gath", image: "/champions/Chogath.png", roles: ["top"] },
	{ id: 25, name: "Corki", image: "/champions/Corki.png", roles: ["mid"] },
	{ id: 26, name: "Darius", image: "/champions/Darius.png", roles: ["top"] },
	{ id: 27, name: "Diana", image: "/champions/Diana.png", roles: ["jungle"] },
	{ id: 28, name: "Dr. Mundo", image: "/champions/DrMundo.png", roles: ["top"] },
	{ id: 29, name: "Draven", image: "/champions/Draven.png", roles: ["adc"] },
	{ id: 30, name: "Ekko", image: "/champions/Ekko.png", roles: ["jungle", "mid"] },
	{ id: 31, name: "Elise", image: "/champions/Elise.png", roles: ["jungle"] },
	{ id: 32, name: "Evelynn", image: "/champions/Evelynn.png", roles: ["jungle"] },
	{ id: 33, name: "Ezreal", image: "/champions/Ezreal.png", roles: ["adc", "mid"] },
	{ id: 34, name: "Fiddlesticks", image: "/champions/Fiddlesticks.png", roles: ["jungle"] },
	{ id: 35, name: "Fiora", image: "/champions/Fiora.png", roles: ["top"] },
	{ id: 36, name: "Fizz", image: "/champions/Fizz.png", roles: ["mid"] },
	{ id: 37, name: "Galio", image: "/champions/Galio.png", roles: ["mid"] },
	{ id: 38, name: "Gangplank", image: "/champions/Gangplank.png", roles: ["top"] },
	{ id: 39, name: "Garen", image: "/champions/Garen.png", roles: ["top"] },
	{ id: 40, name: "Gnar", image: "/champions/Gnar.png", roles: ["top"] },
	{ id: 41, name: "Gragas", image: "/champions/Gragas.png", roles: ["top", "jungle"] },
	{ id: 42, name: "Graves", image: "/champions/Graves.png", roles: ["jungle"] },
	{ id: 43, name: "Gwen", image: "/champions/Gwen.png", roles: ["top"] },
	{ id: 44, name: "Hecarim", image: "/champions/Hecarim.png", roles: ["jungle"] },
	{ id: 45, name: "Heimerdinger", image: "/champions/Heimerdinger.png", roles: ["support"] },
	{ id: 46, name: "Hwei", image: "/champions/Hwei.png", roles: ["mid", "support"] },
	{ id: 47, name: "Illaoi", image: "/champions/Illaoi.png", roles: ["top"] },
	{ id: 48, name: "Irelia", image: "/champions/Irelia.png", roles: ["top", "mid"] },
	{ id: 49, name: "Ivern", image: "/champions/Ivern.png", roles: ["jungle"] },
	{ id: 50, name: "Janna", image: "/champions/Janna.png", roles: ["support"] },
	{ id: 51, name: "Jarvan IV", image: "/champions/JarvanIV.png", roles: ["jungle"] },
	{ id: 52, name: "Jax", image: "/champions/Jax.png", roles: ["top"] },
	{ id: 53, name: "Jayce", image: "/champions/Jayce.png", roles: ["top"] },
	{ id: 54, name: "Jhin", image: "/champions/Jhin.png", roles: ["adc"] },
	{ id: 55, name: "Jinx", image: "/champions/Jinx.png", roles: ["adc"] },
	{ id: 56, name: "K'Sante", image: "/champions/Ksante.png", roles: ["top"] },
	{ id: 57, name: "Kai'Sa", image: "/champions/Kaisa.png", roles: ["adc", "mid"] },
	{ id: 58, name: "Kalista", image: "/champions/Kalista.png", roles: ["adc"] },
	{ id: 59, name: "Karma", image: "/champions/Karma.png", roles: ["support"] },
	{ id: 60, name: "Karthus", image: "/champions/Karthus.png", roles: ["jungle"] },
	{ id: 61, name: "Kassadin", image: "/champions/Kassadin.png", roles: ["mid"] },
	{ id: 62, name: "Katarina", image: "/champions/Katarina.png", roles: ["mid"] },
	{ id: 63, name: "Kayle", image: "/champions/Kayle.png", roles: ["top"] },
	{ id: 64, name: "Kayn", image: "/champions/Kayn.png", roles: ["jungle"] },
	{ id: 65, name: "Kennen", image: "/champions/Kennen.png", roles: ["top"] },
	{ id: 66, name: "Kha'Zix", image: "/champions/Khazix.png", roles: ["jungle"] },
	{ id: 67, name: "Kindred", image: "/champions/Kindred.png", roles: ["jungle"] },
	{ id: 68, name: "Kled", image: "/champions/Kled.png", roles: ["top"] },
	{ id: 69, name: "Kog'Maw", image: "/champions/KogMaw.png", roles: ["adc"] },
	{ id: 70, name: "LeBlanc", image: "/champions/Leblanc.png", roles: ["mid"] },
	{ id: 71, name: "Lee Sin", image: "/champions/LeeSin.png", roles: ["jungle"] },
	{ id: 72, name: "Leona", image: "/champions/Leona.png", roles: ["support"] },
	{ id: 73, name: "Lillia", image: "/champions/Lillia.png", roles: ["jungle"] },
	{ id: 74, name: "Lissandra", image: "/champions/Lissandra.png", roles: ["mid"] },
	{ id: 75, name: "Lucian", image: "/champions/Lucian.png", roles: ["adc"] },
	{ id: 76, name: "Lulu", image: "/champions/Lulu.png", roles: ["support"] },
	{ id: 77, name: "Lux", image: "/champions/Lux.png", roles: ["support", "mid"] },
	{ id: 78, name: "Malphite", image: "/champions/Malphite.png", roles: ["top"] },
	{ id: 79, name: "Malzahar", image: "/champions/Malzahar.png", roles: ["mid"] },
	{ id: 80, name: "Maokai", image: "/champions/Maokai.png", roles: ["jungle"] },
	{ id: 81, name: "Master Yi", image: "/champions/MasterYi.png", roles: ["jungle"] },
	{ id: 82, name: "Mel", image: "/champions/Mel.png", roles: ["support", "mid"] },
	{ id: 83, name: "Milio", image: "/champions/Milio.png", roles: ["support"] },
	{ id: 84, name: "Miss Fortune", image: "/champions/MissFortune.png", roles: ["adc"] },
	{ id: 85, name: "Mordekaiser", image: "/champions/Mordekaiser.png", roles: ["top"] },
	{ id: 86, name: "Morgana", image: "/champions/Morgana.png", roles: ["support"] },
	{ id: 87, name: "Naafiri", image: "/champions/Naafiri.png", roles: ["jungle", "mid"] },
	{ id: 88, name: "Nami", image: "/champions/Nami.png", roles: ["support"] },
	{ id: 89, name: "Nasus", image: "/champions/Nasus.png", roles: ["top"] },
	{ id: 90, name: "Nautilus", image: "/champions/Nautilus.png", roles: ["support"] },
	{ id: 91, name: "Neeko", image: "/champions/Neeko.png", roles: ["mid", "support"] },
	{ id: 92, name: "Nidalee", image: "/champions/Nidalee.png", roles: ["jungle"] },
	{ id: 93, name: "Nilah", image: "/champions/Nilah.png", roles: ["adc"] },
	{ id: 94, name: "Nocturne", image: "/champions/Nocturne.png", roles: ["jungle"] },
	{ id: 95, name: "Nunu & Willump", image: "/champions/Nunu.png", roles: ["jungle"] },
	{ id: 96, name: "Olaf", image: "/champions/Olaf.png", roles: ["top"] },
	{ id: 97, name: "Orianna", image: "/champions/Orianna.png", roles: ["mid"] },
	{ id: 98, name: "Ornn", image: "/champions/Ornn.png", roles: ["top"] },
	{ id: 99, name: "Pantheon", image: "/champions/Pantheon.png", roles: ["top", "mid", "support"] },
	{ id: 100, name: "Poppy", image: "/champions/Poppy.png", roles: ["top", "jungle"] },
	{ id: 101, name: "Pyke", image: "/champions/Pyke.png", roles: ["support"] },
	{ id: 102, name: "Qiyana", image: "/champions/Qiyana.png", roles: ["mid"] },
	{ id: 103, name: "Quinn", image: "/champions/Quinn.png", roles: ["top"] },
	{ id: 104, name: "Rakan", image: "/champions/Rakan.png", roles: ["support"] },
	{ id: 105, name: "Rammus", image: "/champions/Rammus.png", roles: ["jungle"] },
	{ id: 106, name: "Rek'Sai", image: "/champions/RekSai.png", roles: ["jungle"] },
	{ id: 107, name: "Rell", image: "/champions/Rell.png", roles: ["support"] },
	{ id: 108, name: "Renata Glasc", image: "/champions/Renata.png", roles: ["support"] },
	{ id: 109, name: "Renekton", image: "/champions/Renekton.png", roles: ["top"] },
	{ id: 110, name: "Rengar", image: "/champions/Rengar.png", roles: ["jungle"] },
	{ id: 111, name: "Riven", image: "/champions/Riven.png", roles: ["top"] },
	{ id: 112, name: "Rumble", image: "/champions/Rumble.png", roles: ["top"] },
	{ id: 113, name: "Ryze", image: "/champions/Ryze.png", roles: ["mid"] },
	{ id: 114, name: "Samira", image: "/champions/Samira.png", roles: ["adc"] },
	{ id: 115, name: "Sejuani", image: "/champions/Sejuani.png", roles: ["jungle"] },
	{ id: 116, name: "Senna", image: "/champions/Senna.png", roles: ["support"] },
	{ id: 117, name: "Seraphine", image: "/champions/Seraphine.png", roles: ["support"] },
	{ id: 118, name: "Sett", image: "/champions/Sett.png", roles: ["top"] },
	{ id: 119, name: "Shaco", image: "/champions/Shaco.png", roles: ["jungle"] },
	{ id: 120, name: "Shen", image: "/champions/Shen.png", roles: ["top"] },
	{ id: 121, name: "Shyvana", image: "/champions/Shyvana.png", roles: ["jungle"] },
	{ id: 122, name: "Singed", image: "/champions/Singed.png", roles: ["top"] },
	{ id: 123, name: "Sion", image: "/champions/Sion.png", roles: ["top"] },
	{ id: 124, name: "Sivir", image: "/champions/Sivir.png", roles: ["adc"] },
	{ id: 125, name: "Skarner", image: "/champions/Skarner.png", roles: ["jungle"] },
	{ id: 126, name: "Smolder", image: "/champions/Smolder.png", roles: ["adc", "mid"] },
	{ id: 127, name: "Sona", image: "/champions/Sona.png", roles: ["support"] },
	{ id: 128, name: "Soraka", image: "/champions/Soraka.png", roles: ["support"] },
	{ id: 129, name: "Swain", image: "/champions/Swain.png", roles: ["support"] },
	{ id: 130, name: "Sylas", image: "/champions/Sylas.png", roles: ["jungle", "mid"] },
	{ id: 131, name: "Syndra", image: "/champions/Syndra.png", roles: ["mid"] },
	{ id: 132, name: "Tahm Kench", image: "/champions/TahmKench.png", roles: ["top"] },
	{ id: 133, name: "Taliyah", image: "/champions/Taliyah.png", roles: ["mid"] },
	{ id: 134, name: "Talon", image: "/champions/Talon.png", roles: ["mid"] },
	{ id: 135, name: "Taric", image: "/champions/Taric.png", roles: ["support"] },
	{ id: 136, name: "Teemo", image: "/champions/Teemo.png", roles: ["top"] },
	{ id: 137, name: "Thresh", image: "/champions/Thresh.png", roles: ["support"] },
	{ id: 138, name: "Tristana", image: "/champions/Tristana.png", roles: ["adc", "mid"] },
	{ id: 139, name: "Trundle", image: "/champions/Trundle.png", roles: ["jungle"] },
	{ id: 140, name: "Tryndamere", image: "/champions/Tryndamere.png", roles: ["top"] },
	{ id: 141, name: "Twisted Fate", image: "/champions/TwistedFate.png", roles: ["mid"] },
	{ id: 142, name: "Twitch", image: "/champions/Twitch.png", roles: ["adc"] },
	{ id: 143, name: "Udyr", image: "/champions/Udyr.png", roles: ["jungle"] },
	{ id: 144, name: "Urgot", image: "/champions/Urgot.png", roles: ["top"] },
	{ id: 145, name: "Varus", image: "/champions/Varus.png", roles: ["adc"] },
	{ id: 146, name: "Vayne", image: "/champions/Vayne.png", roles: ["adc"] },
	{ id: 147, name: "Veigar", image: "/champions/Veigar.png", roles: ["mid"] },
	{ id: 148, name: "Vel'Koz", image: "/champions/Velkoz.png", roles: ["support"] },
	{ id: 149, name: "Vex", image: "/champions/Vex.png", roles: ["mid"] },
	{ id: 150, name: "Vi", image: "/champions/Vi.png", roles: ["jungle"] },
	{ id: 151, name: "Viego", image: "/champions/Viego.png", roles: ["jungle"] },
	{ id: 152, name: "Viktor", image: "/champions/Viktor.png", roles: ["mid"] },
	{ id: 153, name: "Vladimir", image: "/champions/Vladimir.png", roles: ["mid"] },
	{ id: 154, name: "Volibear", image: "/champions/Volibear.png", roles: ["top"] },
	{ id: 155, name: "Warwick", image: "/champions/Warwick.png", roles: ["jungle"] },
	{ id: 156, name: "Wukong", image: "/champions/Wukong.png", roles: ["jungle"] },
	{ id: 157, name: "Xayah", image: "/champions/Xayah.png", roles: ["adc"] },
	{ id: 158, name: "Xerath", image: "/champions/Xerath.png", roles: ["support"] },
	{ id: 159, name: "Xin Zhao", image: "/champions/XinZhao.png", roles: ["jungle"] },
	{ id: 160, name: "Yasuo", image: "/champions/Yasuo.png", roles: ["top", "mid"] },
	{ id: 161, name: "Yone", image: "/champions/Yone.png", roles: ["top", "mid"] },
	{ id: 162, name: "Yorick", image: "/champions/Yorick.png", roles: ["top"] },
	{ id: 163, name: "Yuumi", image: "/champions/Yuumi.png", roles: ["support"] },
	{ id: 164, name: "Zaahen", image: "/champions/Zaahen.png", roles: ["top"] },
	{ id: 165, name: "Zac", image: "/champions/Zac.png", roles: ["jungle"] },
	{ id: 166, name: "Zed", image: "/champions/Zed.png", roles: ["mid"] },
	{ id: 167, name: "Zeri", image: "/champions/Zeri.png", roles: ["adc"] },
	{ id: 168, name: "Ziggs", image: "/champions/Ziggs.png", roles: ["mid"] },
	{ id: 169, name: "Zilean", image: "/champions/Zilean.png", roles: ["support"] },
	{ id: 170, name: "Zoe", image: "/champions/Zoe.png", roles: ["mid"] },
	{ id: 171, name: "Zyra", image: "/champions/Zyra.png", roles: ["support"] }
];
